/**
 * Result of validating a UPI Virtual Payment Address (VPA).
 */
export interface UpiValidationResult {
  /** Whether the UPI ID is structurally valid */
  isValid: boolean;
  /** The normalized UPI ID (lowercase) or the original string if invalid */
  vpa: string;
  /** The username/account prefix part of the UPI ID (before '@') */
  username: string;
  /** The handle/bank identifier part of the UPI ID (after '@') */
  handle: string;
  /** Name of the bank or payment app associated with the handle, if recognized */
  provider?: string;
  /** Whether the handle exists in the NPCI registered bank/app handles database */
  isKnownHandle: boolean;
  /** Explanation of why validation failed, if invalid */
  error?: string;
}

/**
 * Handle category classification.
 */
export type UpiHandleCategory =
  | "app"
  | "bank"
  | "fintech"
  | "payments-bank"
  | "small-finance-bank"
  | "cooperative-bank"
  | "regional-rural-bank";

/**
 * Detailed metadata for an official NPCI UPI handle.
 */
export interface UpiHandleInfo {
  /** The handle without '@' (e.g. "okhdfcbank", "paytm", "ybl") */
  handle: string;
  /** Primary consumer-facing provider name (e.g. "Google Pay", "PhonePe", "Paytm") */
  provider: string;
  /** Underlying sponsor or partner bank (e.g. "HDFC Bank", "YES Bank") */
  bank?: string;
  /** Category of provider */
  category: UpiHandleCategory;
}

/**
 * Options for generating an official NPCI UPI Intent URI (`upi://pay`).
 */
export interface UpiIntentOptions {
  /** Payee Virtual Payment Address (VPA) / UPI ID (e.g. "merchant@okaxis") */
  pa: string;
  /** Payee Name (e.g. "Acme Corp" or "Vijay Misal") */
  pn: string;
  /** Merchant Category Code (4 digits, e.g. "5411") */
  mc?: string;
  /** Transaction Reference ID generated by merchant */
  tr?: string;
  /** Transaction ID */
  tid?: string;
  /** Transaction Note / Description */
  tn?: string;
  /** Transaction amount (e.g. 1500 or "1500.50"). Will be formatted to 2 decimal places */
  am?: number | string;
  /** Currency code (Defaults to "INR") */
  cu?: string;
  /** Reference URL with transaction details */
  url?: string;
  /** Minimum Amount to be paid in case of variable bill payment */
  mam?: number | string;
  /** Transaction initiation mode (e.g. "00", "01", "04") */
  mode?: string;
  /** NPCI-assigned Organization ID */
  orgid?: string;
  /** Digital signature (base64 encoded) for verified merchant intent */
  sign?: string;
}

/**
 * Parsed and validated data extracted from a `upi://pay` URI.
 */
export interface UpiIntentData {
  /** The full input URI */
  rawUri: string;
  /** Payee Virtual Payment Address */
  pa: string;
  /** Payee Name */
  pn: string;
  /** Merchant Category Code */
  mc?: string;
  /** Transaction Reference ID */
  tr?: string;
  /** Transaction ID */
  tid?: string;
  /** Transaction Note */
  tn?: string;
  /** Numeric parsed amount */
  am?: number;
  /** Formatted string amount */
  amString?: string;
  /** Currency code (typically "INR") */
  cu: string;
  /** Reference URL */
  url?: string;
  /** Minimum amount numeric */
  mam?: number;
  /** Minimum amount string */
  mamString?: string;
  /** Transaction initiation mode */
  mode?: string;
  /** Organization ID */
  orgid?: string;
  /** Digital signature */
  sign?: string;
  /** Additional or vendor-specific query parameters present in the URI */
  otherParams: Record<string, string>;
  /** VPA validation result for the payee address */
  validationResult: UpiValidationResult;
}
